### PR TITLE
Spontaneous events callbacks

### PR DESCRIPTION
**Pull request by haku**
Possible solution for feature discussed in issue #19.
Please review at your convenience.
Feel free to tell me to change stuff. :)

### CODE REVIEW

**Comment by vitalidze** [comment]
Sorry for the delay. Please read my comments. This commit https://github.com/haku/chromecast-java-api-v2/commit/e5b0a16659d2a8248596e11bd189c9d0fea40d95 looks fine, another one requires some updates.

**Comment by haku** [comment]
The `EventListenerHolder` parameter on Channel is because it needs to be the same instance that the `ChromeCast` instance has.  This way if the `ChromeCast` disconnects and reconnects again any previously added listeners are still present.

I used `CopyOnWriteArraySet` just because it seemed like the right tool.  The list of listeners is rarely going to be changed but very frequently read and iterated over.  While the chance of a listener being added or removed in one thread while being iterated over to invoke in another is low, it seemed prudent to protect against.  Using a `Set` from `java.util.concurrent` avoids the need to synchronise every time a listener is invoked.

I have restructured the way events are passed to the the listeners so they are wrapped in `ChromeCastSpontaneousEvent`.  Please let me know what you think.

**Comment by vitalidze** [comment]
> The EventListenerHolder parameter on Channel is because it needs to be the same instance that the ChromeCast instance has. This way if the ChromeCast disconnects and reconnects again any previously added listeners are still present.
>
> I used CopyOnWriteArraySet just because it seemed like the right tool. The list of listeners is rarely going to be changed but very frequently read and iterated over. While the chance of a listener being added or removed in one thread while being iterated over to invoke in another is low, it seemed prudent to protect against. Using a Set from java.util.concurrent avoids the need to synchronise every time a listener is invoked.

This is fine. Let's leave it.

> I have restructured the way events are passed to the the listeners so they are wrapped in ChromeCastSpontaneousEvent. Please let me know what you think.
 Show all checks

Well, I don't quite understand why you have created an hierarchy of events. I think you should either use enumeration to detect event type or hierarchy. I prefer enumeration. You can encapsulate logic to get the actual object right into enumeration element. It's up to you how to implement this, but I insist to have a single way - either enums or hierarchy of classes.

**Comment by haku** [comment]
I have removed the hierarchy of sub-classes.
Tired me last night made things more complex than they needed to be.

**Comment by vitalidze** [comment]
Merged. Thank you.

**Pull request merged**
