### PR TITLE
add iconUrl field to the Application object

### PR DESCRIPTION
**Pull request by ScottAlbertine**
I looked at the raw JSON and there is now an iconUrl field that's added to the Application object in the JSON. This is very handy.

### CODE REVIEW

**Comment by vitalidze** [comment]
Thank you for sending the PR. Is it possible to write a small and simple unit-test? It would be great to take real-life JSON to minimise regression in newest version.

**Comment by ScottAlbertine** [comment]
Added it, checked a bunch of other fields while I was in there. The travis build has been going for 10 minutes now, and normally only takes 2, but I don't have permission to stop and restart it. The build runs fine on my local machine.

**Comment by vitalidze** [comment]
Thank you. I restarted build at it completed without any issues. Not sure what happened, but it seems that it stuck at downloading maven dependencies.

**Comment by vitalidze** [comment]
Merged. Thank you very much for the cooperation. Will be included in nearest minor release.

**Comment by vitalidze** [comment]
Change set was included in just released version 0.11.1, which will become available today.

**Pull request merged**
