### PR TITLE
Suport for sending raw cast requests

### PR DESCRIPTION
**Pull request by emlove**
## Description
This PR adds a new method to support sending raw requests of pre-serialized JSON, and returns the raw JSON string as the response. I doubt this is a common use case, but would be necessary to make use of this lib with microG. In this environment, Google's SDK has already serialized the request that it wants to make, and already is equipped to parse the response.

Intended usage is here: https://github.com/microg/android_packages_apps_GmsCore/pull/555/files#diff-dd605a7b4a2ad9bbac1db8fc15690fa1R85

### CODE REVIEW

**Comment by vitalidze** [comment]
Thanks for the PR. For me it's not clear why you need to send the RAW JSON. Can you please give some details on the use case? I have tried reading code from the URL, but it does not make much sense for me. Please excuse me if I missed something.

Also generating `requestId` by the user seems for me a non fault-proof approach.

**Comment by armills** [comment]
Sure. The microG project is an open-source reimplementation of the proprietary Google Play Services that runs on Android devices. Because we're reimplementing reverse engineered APIs, we don't have control over the outward facing API we need to implement. For example, the signature for the `sendMessage` method linked above is part of the API we don't control, but just have to implement.

I absolutely agree that depending on downstream implementations to generate their own `requestId`s isn't ideal, but unfortunately in our case we don't have any choice but to trust that we're getting appropriate `requestId`s when the `sendMessage` is called by code we don't control and pass the requests through.

Does that make senese?

**Comment by vitalidze** [comment]
So, in other words the API that you don't control receives the string messages in JSON format? Then you have to pass these messages to Chromecast device, right?

**Comment by armills** [comment]
Yep that's right.

This could also be migrated into a fork as well if you don't think it's appropriate for this lib, since it's definitely outside the scope of what you have so far. I'd just rather avoid fragmentation if possible.

**Comment by vitalidze** [comment]
If so, then I suppose that using custom request/response along with `JsonAnyGetter` and `JsonAnySetter` may work for your generic dynamic requests. See [this article](https://www.concretepage.com/jackson-api/jackson-jsonanygetter-and-jsonanysetter-example) for example. Does it make any sense for your use case?

**Comment by armills** [comment]
I think I'm going to just leave this on hold for the moment, until I get my microg branch more complete. Once that branch is closer to ready I can circle back and see exactly what I'll need from this API, and evaluate some of these options with better knowledge of what the final usage is going to look like.

**Comment by vitalidze** [comment]
Sounds good. Thank you.

**Comment by armills** [comment]
OK, I took a look at the JsonAnyGetter and JsonAnySetter, and I don't think those will do quite what I'll need, since they are still built around getting everything underneath a key, instead of the entire JSON object.

**Comment by ale5000-git** [comment]
@vitalidze: Any update on this?

**Comment by vitalidze** [comment]
@ale5000-git no updates so far. I still don't have my own understanding why would one need to mess up with sending plain strings instead of working with POJOs. 

Do you have an example where you cannot use already existing custom objects for exchange with your service?

**Comment by ale5000-git** [comment]
The example is here => https://github.com/microg/android_packages_apps_GmsCore/pull/555/files

**Comment by vitalidze** [comment]
@ale5000-git  this does not make much sense. I suppose you are talking about listeners that do accept messages in string format:

1. What are the contents of the string message? 
2. Why it is generic? In other words why you don't know the structure of received messages?
3. From the consumer standpoint what it does with the generic message? 
4. How can you even implement a consumer that does not know how to process messages?

**Comment by ale5000-git** [comment]
An app that is compiled with Google Play Services libraries expect certain "APIs" to be present in Google Play Services.

microG GmsCore is a reimplementation of Google Play Services.
The user remove Google Play Services and install microG GmsCore and apps shouldn't notice the difference (teorically).

microG GmsCore is only a library in the middle, it don't know what the app will do:
Any app => microG GmsCore => functions like GCM or Cast or other

This is a generic explanation, @armills know the detail of the cast function needed in microG GmsCore.

**Pull request closed without merging**
