### PR TITLE
Update ChromeCast.java

### PR DESCRIPTION
**Pull request by MCMastery**
The load(String, String, String, String) method is broken. It should be "title", not "title:" (I've tested this)

### CODE REVIEW

**Comment by vitalidze** [comment]
Does it work fine then with both video/audio streams and default receiver?

**Comment by vitalidze** [comment]
Can you please write a test for this case?

**Comment by maggu2810** [comment]
What's the default receiver?
This one `private static final String MEDIA_PLAYER = "CC1AD845";`?

Then I could give it a try and load a audio + video stream given a title (I assume the title should be displayed on my TV, then).

**Comment by vitalidze** [comment]
> What's the default receiver?
> This one private static final String MEDIA_PLAYER = "CC1AD845";?

Default receiver is the default media renderer application from google (I guess): https://developers.google.com/cast/docs/receiver_apps#default

> Then I could give it a try and load a audio + video stream given a title (I assume the title should be displayed on my TV, then).

Correct.

**Comment by maggu2810** [comment]
My tests didn't succeed. It fails with and without the colon.

After that I tested pycromcast and realized that the title is working there.
So I looked at the code.
In the pychromecast's code the title and the thumb is set using the metadata of the media.

I changed the Java code and using the metadata, the title is displayed (I have no thumb).

```diff
diff --git a/src/main/java/su/litvak/chromecast/api/v2/ChromeCast.java b/src/main/java/su/litvak/chromecast/api/v2/ChromeCast.java
index c3dd601..3e5d918 100644
--- a/src/main/java/su/litvak/chromecast/api/v2/ChromeCast.java
+++ b/src/main/java/su/litvak/chromecast/api/v2/ChromeCast.java
@@ -245,10 +245,10 @@ public class ChromeCast {
      */
     public MediaStatus load(String title, String thumb, String url, String contentType) throws IOException {
         Status status = getStatus();
-        Map<String, String> customData = new HashMap<String, String>(2);
-        customData.put("title", title);
-        customData.put("thumb", thumb);
-        return channel.load(status.getRunningApp().transportId, status.getRunningApp().sessionId, new Media(url, contentType), true, 0d, customData);
+        Map<String, Object> metadata = new HashMap<String, Object>(2);
+        metadata.put("title", title);
+        metadata.put("thumb", thumb);
+        return channel.load(status.getRunningApp().transportId, status.getRunningApp().sessionId, new Media(url, contentType, null, null, null, metadata, null, null), true, 0d, null);
     }
```

**Comment by maggu2810** [comment]
Here are the code lines of `pychromecast`:
https://github.com/balloob/pychromecast/blob/15398bb/pychromecast/controllers/media.py#L443

WDYT?

**Comment by vitalidze** [comment]
I think it's better to leave a working solution with `metadata`.

**Comment by vitalidze** [comment]
Merged working solution from #50 instead

**Pull request closed without merging**
