### PR TITLE
add some toString() methods for logging

### PR DESCRIPTION
**Pull request by maggu2810**
Signed-off-by: Markus Rathgeb <maggu2810@gmail.com>

### CODE REVIEW

**Comment by vitalidze** [comment]
Please implement it in a same way as it is done for `Volume`, `Item` and `Media` classes (i.e. use `String.format()`) for uniformity.

**Comment by maggu2810** [comment]
Do you also want to drop the variable names?
I assume it is not common readable for e.g. MediaStatus as it contains a lot of members.
WDYT?

**Comment by maggu2810** [comment]
@vitalidze ping...

I changed the toString() methods so it fits to `Volume`, `Item` and `Media`.
I still miss your reply about the variable names.

I am also not sure how you would like to format Collections.

**Comment by vitalidze** [comment]
> I still miss your reply about the variable names.

It makes sense to add variable names, I think colon separated, something like this:

````
Media{url: %s, contentType: %s, duration: %s}
````

If you agree with such format then please if possible change it everywhere.

Thank you!

**Comment by vitalidze** [comment]
One little addition: I think such format is applicable only for classes with more than one field. For example for `Namespace` I think we can just leave the `Namespace{%s}` format.

**Comment by vitalidze** [comment]
Looks good to me. Merged. Thank you very much!

**Pull request merged**
